title: Cub Scout Pack 338 Seattle
description: Join Cub Scout Pack 338 in Seattle, WA! Open to kids of any gender from Kindergarten through 5th grade.
url: "https://chrismetcalf.github.io"
baseurl: "/pack338seattle.org"

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - .vendor/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - README.md
